---
title: "Backlog Management Index"
author: "Mark Ofori-Kyei"
date: "July 3, 2016"
output: ioslides_presentation
---


## This application calculates the Backlog Management Index (BMI). BMI is a very good indication of the success of the project work and an understanding of the stability and control.

- (problems closed during the month * 100) / (problems opened during the month)


## Two Key Inputs for Calculating BMI

- Enter the problems closed during the month
- Enter the problems opened during the month
- Press the submit button



## Problems closed during the month is a count of all problems that have been totally resolved during the month

- Include all problem requests closed in the month
- Include all Work orders closed in the month
- Verify your entry on the right hand panel



## Problems opened during the month is a count of all new problems that have been opened during the month

- Include all problem requests opened in the month
- Include all Work orders opened in the month
- Verify your entry on the right hand panel

## BMI is calculated based on your inputs

- Example: If you enter 58 for problems closed in the month
- Example: If you enter 45 for problems opened in the month
- Review the result of the BMI calculation
```{r}
(58 * 100)/45
```
